### ISSUE TITLE
Write docs

### ISSUE THREAD

**Issue by dialexo** [clicepfl/clic-website#51]
- [ ] News component for editors see #11 
- [ ] Sponsors component for editors see #37 
- [ ] Gallery component for editors see #46 
- [ ] Templating in src/components see #4 
- [x] General markdown docs (file structure, compile / run instructions, ...) see #2 
- [ ] SASS documentation (sassdocs?) see #3

**Comment by dialexo** [comment]
Will update accordingly with new architecture
